version: '3.8'

services:
  app:
    container_name: prodigiosovolcan
    image: node:20.11.1
    restart: always
    environment:
      MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      FRONT_URL: ${FRONT_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
    volumes:
      - .:/src
    working_dir: /src
    command: bash -c "npm run dev"
    ports:
      - 9778:9778

    depends_on:
      - mongo-db

  mongo-db:
    container_name: mongo
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017
